"""added tokens table

Revision ID: b1795ff99f51
Revises: 741edf06c9d3
Create Date: 2024-10-24 18:13:21.968087

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b1795ff99f51'
down_revision: Union[str, None] = '741edf06c9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('token', sa.String(length=1024), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.add_column('answers', sa.Column('blocked', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('blocked', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('blocked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=True))
    op.drop_column('users', 'refresh_token')
    op.drop_column('users', 'status_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'banned')
    op.drop_column('posts', 'blocked')
    op.drop_column('comments', 'blocked')
    op.drop_column('answers', 'blocked')
    op.drop_table('tokens')
    # ### end Alembic commands ###
