"""added answer_delay field

Revision ID: de398f104c5c
Revises: b1795ff99f51
Create Date: 2024-10-25 10:51:04.274841

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'de398f104c5c'
down_revision: Union[str, None] = 'b1795ff99f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('answer_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'answer_delay')
    # ### end Alembic commands ###
