name: Check-Import-Sorting

on: [push]

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort==5.13.2

      - name: Run isort check
        run: isort --check-only --diff .
